---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vote-ci
spec:
  pipelineRef:
    name: instavote-ci
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: harbor-creds
  params:
  - name: repoUrl
    value: https://github.com/afmaghribi/LFD254-mini-project-1
  - name: revision
    value: main
  - name: sparseCheckoutDirectories
    value: example-voting-app/vote/
  - name: imageUrl
    value: 81.81.81.11:1337/tekton/vote
  - name: pathToContext
    value: example-voting-app/vote
  - name: EXTRA_ARGS
    value: --insecure-skip-tls-verify
